// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcLThZL2lj6-qYkV-v7c4ZIhrwEveNi1w',
    appId: '1:436015251986:web:ee5198361453ea34a18ecb',
    messagingSenderId: '436015251986',
    projectId: 'ecommerceapp-4e5ae',
    authDomain: 'ecommerceapp-4e5ae.firebaseapp.com',
    storageBucket: 'ecommerceapp-4e5ae.appspot.com',  
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqwcxec7UDlmSlxyxwZReNMHvwMt2-ZVk',
    appId: '1:436015251986:android:b38f9f2bac159c4aa18ecb',
    messagingSenderId: '436015251986',
    projectId: 'ecommerceapp-4e5ae',
    storageBucket: 'ecommerceapp-4e5ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd1hVF51RVib6vP96MVtY_25jPuxePA-c',
    appId: '1:436015251986:ios:ae74982ce3aa67b5a18ecb',
    messagingSenderId: '436015251986',
    projectId: 'ecommerceapp-4e5ae',
    storageBucket: 'ecommerceapp-4e5ae.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd1hVF51RVib6vP96MVtY_25jPuxePA-c',
    appId: '1:436015251986:ios:ae74982ce3aa67b5a18ecb',
    messagingSenderId: '436015251986',
    projectId: 'ecommerceapp-4e5ae',
    storageBucket: 'ecommerceapp-4e5ae.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcLThZL2lj6-qYkV-v7c4ZIhrwEveNi1w',
    appId: '1:436015251986:web:1e500de55b3b478ba18ecb',
    messagingSenderId: '436015251986',
    projectId: 'ecommerceapp-4e5ae',
    authDomain: 'ecommerceapp-4e5ae.firebaseapp.com',
    storageBucket: 'ecommerceapp-4e5ae.appspot.com',
  );
}
